### ISSUE TITLE
Create a github action that allows workflow_dispatch and workflow_call invocation to upload Kolibri to kolibri-proposed PPA

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri-installer-debian#133]
[PLACEHOLDER/DRAFT - TBC]

# Goal

The aim here is to allow automated releases to kolibri-proposed - this will mean that both releases and pre-releases should be able to be uploaded to kolibri-proposed as part of a Github Action.

# Implementation

Similar to the build_deb.yml action in this repository, the required input will be a tar file - whether it is the URL of a tar file, or a tar file name that can be downloaded using the github download artifact action.

e.g.
```
name: Release to kolibri-proposed PPA

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tar-url:
        description: 'URL for Kolibri tar file'
        required: true
  workflow_call:
    inputs:
      tar-file-name:
        required: true
        type: string
      ref:
        description: 'A ref for this workflow to check out its own repo'
        required: true
        type: string
```
